"""Integration tests comparing Python DAS output against MATLAB reference.

Requires matlab_reference.h5 generated by generate_matlab_reference.m.
Run with: pytest tests/test_integration_matlab.py -v
"""

import os
import numpy as np
import pytest
import h5py

REFERENCE_FILE = os.path.join(os.path.dirname(__file__), "matlab_reference.h5")
DATA_FILE = os.path.join(os.path.dirname(__file__), "..", "..", "data",
                         "Verasonics_P2-4_parasternal_long_small.uff")

pytestmark = pytest.mark.skipif(
    not os.path.exists(REFERENCE_FILE) or not os.path.exists(DATA_FILE),
    reason="MATLAB reference data or UFF dataset not available"
)


@pytest.fixture(scope="module")
def matlab_ref():
    """Load MATLAB reference data."""
    with h5py.File(REFERENCE_FILE, "r") as f:
        return {
            "scan_x": f["scan/x"][:].ravel(),
            "scan_y": f["scan/y"][:].ravel(),
            "scan_z": f["scan/z"][:].ravel(),
            "transmit_delay": f["transmit_delay"][:].T,
            "receive_delay": f["receive_delay"][:].T,
            "bf_real": f["beamformed_data_real"][:].T,
            "bf_imag": f["beamformed_data_imag"][:].T,
            "N_pixels": int(np.squeeze(f["N_pixels"][()])),
            "N_waves": int(np.squeeze(f["N_waves"][()])),
            "N_channels": int(np.squeeze(f["N_channels"][()])),
        }


@pytest.fixture(scope="module")
def python_result(matlab_ref):
    """Run Python DAS on the same dataset with matching parameters."""
    from pyuff_ustb.objects.uff import Uff
    from pyuff_ustb.objects import SectorScan
    from pyuff_ustb.objects.point import Point
    from ustb.midprocess import DAS
    from ustb.enums import Dimension, Window

    uff_file = Uff(DATA_FILE)
    channel_data = uff_file.read("channel_data")

    sequence = channel_data.sequence
    if not isinstance(sequence, (list, tuple)):
        sequence = [sequence]

    depth_axis = np.linspace(0e-3, 110e-3, 128)
    first_az = float(sequence[0].source.azimuth)
    last_az = float(sequence[-1].source.azimuth)
    azimuth_axis = np.linspace(first_az, last_az, len(sequence))

    scan = SectorScan()
    scan.__dict__["azimuth_axis"] = azimuth_axis
    scan.__dict__["depth_axis"] = depth_axis
    origin = Point()
    origin.__dict__["distance"] = np.float64(0.0)
    origin.__dict__["azimuth"] = np.float64(0.0)
    origin.__dict__["elevation"] = np.float64(0.0)
    scan.__dict__["origin"] = origin

    mid = DAS()
    mid.channel_data = channel_data
    mid.dimension = Dimension.both
    mid.scan = scan
    mid.transmit_apodization.window = Window.scanline
    mid.receive_apodization.window = Window.none
    b_data = mid.go()

    return {
        "scan_x": scan.x.ravel(),
        "scan_z": scan.z.ravel(),
        "transmit_delay": mid.transmit_delay,
        "receive_delay": mid.receive_delay,
        "bf_data": b_data.data,
    }


class TestScanCoordinates:
    def test_should_have_same_range_x(self, matlab_ref, python_result):
        """X coordinate ranges should match (ordering may differ due to meshgrid vs ndgrid)."""
        ml_x = np.sort(matlab_ref["scan_x"])
        py_x = np.sort(python_result["scan_x"])
        np.testing.assert_allclose(ml_x, py_x, atol=1e-6,
                                   err_msg="Scan x coordinate ranges differ")

    def test_should_have_same_range_z(self, matlab_ref, python_result):
        """Z coordinate ranges should match."""
        ml_z = np.sort(matlab_ref["scan_z"])
        py_z = np.sort(python_result["scan_z"])
        np.testing.assert_allclose(ml_z, py_z, atol=1e-6,
                                   err_msg="Scan z coordinate ranges differ")


class TestReceiveDelay:
    def test_should_have_same_delay_value_set(self, matlab_ref, python_result):
        """Receive delay values should cover the same range (pixel ordering may differ)."""
        py_sorted = np.sort(python_result["receive_delay"].ravel())
        ml_sorted = np.sort(matlab_ref["receive_delay"].ravel())
        np.testing.assert_allclose(
            py_sorted, ml_sorted, rtol=1e-4, atol=1e-8,
            err_msg="Receive delay value sets differ"
        )


class TestTransmitDelay:
    def test_should_have_similar_nonzero_delay_statistics(self, matlab_ref, python_result):
        """Non-zero transmit delay statistics should be similar."""
        py_d = python_result["transmit_delay"].ravel()
        ml_d = matlab_ref["transmit_delay"].ravel()
        py_nz = py_d[np.abs(py_d) > 1e-8]
        ml_nz = ml_d[np.abs(ml_d) > 1e-8]
        assert len(py_nz) > 0 and len(ml_nz) > 0, "Should have non-zero delays"
        np.testing.assert_allclose(np.mean(np.abs(py_nz)), np.mean(np.abs(ml_nz)),
                                   rtol=0.1, err_msg="Mean abs transmit delay differs")


class TestBeamformedOutput:
    def test_should_have_matching_shape(self, matlab_ref, python_result):
        ml_shape = matlab_ref["bf_real"].shape
        py_shape = python_result["bf_data"].shape
        assert py_shape[0] == ml_shape[0], (
            f"Pixel count mismatch: Python {py_shape[0]} vs MATLAB {ml_shape[0]}"
        )

    def test_should_have_similar_dynamic_range(self, matlab_ref, python_result):
        """Both outputs should span a similar dynamic range."""
        ml_bf = matlab_ref["bf_real"] + 1j * matlab_ref["bf_imag"]
        ml_env = np.abs(ml_bf).ravel()
        py_env = np.abs(python_result["bf_data"]).ravel()

        ml_dr = 20 * np.log10(ml_env.max() / (np.median(ml_env) + 1e-20))
        py_dr = 20 * np.log10(py_env.max() / (np.median(py_env) + 1e-20))
        assert abs(ml_dr - py_dr) < 15, (
            f"Dynamic range differs: MATLAB {ml_dr:.1f} dB, Python {py_dr:.1f} dB"
        )

    def test_should_have_correlated_sorted_envelopes(self, matlab_ref, python_result):
        """Sorted envelopes should be correlated (pixel ordering may differ
        due to meshgrid vs ndgrid in sector scan)."""
        ml_bf = matlab_ref["bf_real"] + 1j * matlab_ref["bf_imag"]
        ml_env = np.sort(np.abs(ml_bf).ravel())
        py_env = np.sort(np.abs(python_result["bf_data"]).ravel())

        n = min(len(ml_env), len(py_env))
        ml_env = ml_env[:n] / (ml_env.max() + 1e-20)
        py_env = py_env[:n] / (py_env.max() + 1e-20)

        correlation = np.corrcoef(ml_env, py_env)[0, 1]
        assert correlation > 0.9, (
            f"Sorted envelope correlation too low: {correlation:.4f}"
        )
