"""Python vs MATLAB, pixel by pixel, against the small committed references.

The references in tests/ci_reference/ are generated by generate_ci_references.m
and stored in single precision, so this comparison can run in CI. It needs the
datasets in data/ (the Python Tests workflow downloads and caches them); the
tests skip when a dataset is missing, so they never start a download.
"""

import os
import numpy as np
import pytest
import h5py

from tests.matlab_compare import match_pixels, assert_pixelwise_match

REF_DIR = os.path.join(os.path.dirname(__file__), "ci_reference")
DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "data")

# (reference file, dataset, example module)
CASES = [
    ("cpwc_linear.h5", "L7_CPWC_193328.uff", "examples.cpwc_linear"),
    ("picmus_experiment_resolution.h5", "PICMUS_experiment_resolution_distortion.uff",
     "examples.picmus_experiment_resolution"),
]


@pytest.mark.parametrize("ref_file, dataset, example", CASES,
                         ids=[case[0].removesuffix(".h5") for case in CASES])
def test_should_match_committed_matlab_reference(ref_file, dataset, example):
    if not os.path.exists(os.path.join(DATA_DIR, dataset)):
        pytest.skip(f"Dataset {dataset} not available in data/")
    import importlib
    import matplotlib
    matplotlib.use("Agg")

    b_data = importlib.import_module(example).main()
    with h5py.File(os.path.join(REF_DIR, ref_file), "r") as f:
        ml_bf = (f["bf_real"][:] + 1j * f["bf_imag"][:]).T  # -> [pixel, ch, wave, frame]
        ml_x, ml_z = f["scan_x"][:], f["scan_z"][:]

    # Coordinates are stored in single precision (~5 nm at 5 cm)
    perm = match_pixels((ml_x, ml_z), (b_data.scan.x, b_data.scan.z), atol=1e-7)
    # Single-precision reference: tolerances as for the full references
    assert_pixelwise_match(ml_bf[perm], b_data.data, ref_file,
                           min_corr=0.99999, max_rel_err=1e-3)
